CombineCommunity/CombineExt

.github/workflows/tests.yml
CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/Partition.swift
Tests/PartitionTests.swift

Partition a publisher's values into two separate publishers of values that match, and don't match, the provided predicate.
```swift
let source = PassthroughSubject<Int, Never>()
let (even, odd) = source.partition { $0 % 2 == 0 }
even.sink(receiveValue: { print("even: \($0)") })
odd.sink(receiveValue: { print("odd: \($0)") })
source.send(1)
source.send(2)
source.send(3)
source.send(4)
source.send(5)
```
```none
odd: 1
even: 2
odd: 3
even: 4
odd: 5
```

Add `partition` operator

---

CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/ZipMany.swift
Tests/WithLatestFromTests.swift
Tests/ZipManyTests.swift

Rough sketch of overloads to allow folks to zip arbitrarily many publishers. I tried to mirror the existing style in the repository, but please feel free to send any and all feedback (no nit too small)! 🙏🏽

Add `Zip` for multiple Publishers

---

CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/Amb.swift
Tests/AmbTests.swift
codecov.yml

The `amb` operator comes from ReactiveX (In RxSwift, RxJava etc it's called `amb`, while in `RxJS` it's called `race`). 
It takes two publishers (or a variadic number of publishers) and mirrors the emissions of the first one to emit an event.
This operator was live coded on my YouTube channel, to anyone interested in the implementation: 
[![Shai's Swift Bits Live: Creating a custom Combine operator](https://img.youtube.com/vi/Vnk4vFyuBGo/0.jpg)](https://www.youtube.com/watch?v=Vnk4vFyuBGo)

Add `amb()` operator

---

CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/RemoveAllDuplicates.swift
Tests/RemoveAllDuplicatesTests.swift

Tidying up and PR’ing `Publisher.removeAllDuplicates` and `.removeAllDuplicates(by:)` from an earlier sketch [on Twitter](https://twitter.com/jasdev/status/1214764966974312448) and as per your mention of [`Observable.distinct` and `.distinct(_:)`](https://github.com/RxSwiftCommunity/RxSwiftExt/blob/1e7a8683f3a8960042caa9b0ad0fc41f1217104d/Source/RxSwift/distinct.swift#L12-L69).

First pass at `Publisher.removeAllDuplicates` and `removeAllDuplicates(by:)`.

---

README.md
Sources/Operators/Create.swift
Tests/CreateTests.swift

This PR includes two improvements to `AnyPublisher.create`:
1. Instead of providing a raw closure, provides a subscriber-like argument with the familiar event-sending syntax of `send(_:)`, `send(completion:)`.
2. Allow providing a `Cancelable`-conforming object as the return of that closure, which is useful to provide cleanup-logic to your custom publisher.
Thanks to @mbrandonw for the great ideas and feedback 🥇🥳

Improve .create ergonomics and add cancelation-handling

---

CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/ShareReplay.swift
Sources/Subjects/ReplaySubject.swift
Tests/ReplaySubjectTests.swift
Tests/ShareReplayTests.swift

h/t to @tcldr for the reference implementation I leaned on and adapted to Shai’s `DemandBuffer` type. 💯

Adds ReplaySubject and Publisher.share(replay:)

---

README.md
Sources/Operators/WithLatestFrom.swift
Tests/WithLatestFromTests.swift

I'm working on creating `withLatestFrom` operators that support more than one publisher.
In RxSwift, I face many scenarios where I need to get the latest values from more than one observable and additionally there is this great [thread](https://github.com/ReactiveX/RxSwift/issues/1973).
Since under the hood, I'm using `combineLatest`, I'm supporting as many publishers as the operator supports (up to four).

🎉 `withLatestFrom` for more than one publisher.

---

Sources/Subjects/ReplaySubject.swift
Tests/ReplaySubjectTests.swift

👋🏽
I found a small inconsistency with how `ReplaySubject` handles double subscribes compared to `CurrentValue-` and `PassthroughSubject` (cc’ing @tcldr, so this is also on Entwine’s radar).
It turns out my initial assumption that double subscribes were ignored wasn’t actually inherent to `Subject`s and is instead a nuance of `Sink`. The folks behind OpenCombine [noticed this](https://github.com/broadwaylamb/OpenCombine/blob/d680f09932fe68942c3d391d6df296d38b9dcd05/Sources/OpenCombine/Subscribers/Subscribers.Sink.swift#L27), too. `Sink`s keep an internal subscription state that prevents subscriptions from doubly coming through.
I dig into this in greater detail [here](https://jasdev.me/publisher-temperature-primer).
We can verify that `Sink` keeps state by instead double subscribing to a …

Fix double-subscribe bug in ReplaySubject.

---

.swiftlint.yml
CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/PrefixDuration.swift
Sources/Operators/WithLatestFrom.swift
Tests/PrefixDurationTests.swift

Also, scouted a couple of linter issues in WithLatestFrom.swift. If you want me to split that out into a separate PR, lemme know. 👌🏽

Adds Publisher.prefix(duration:tolerance:on:in:options:)

---

README.md
Sources/Operators/Amb.swift
Tests/AmbTests.swift

@klundberg’s question in #reactive yesterday reminded me that we should probably add a `Collection` overlay for `amb`.

Adds Collection.amb.

---

CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Models/ObjectOwnership.swift
Sources/Operators/AssignOwnership.swift
Sources/Operators/AssignToMany.swift
Tests/AssignOwnershipTests.swift
Tests/AssignToManyTests.swift

Using `assign(to:)` might produce a memory leak because it creates a strong reference to `object` (there is a great topic on [swift forums](https://forums.swift.org/t/does-assign-to-produce-memory-leaks/29546/2) about this). I think it might be useful to have `assignWeakly(to:)` operator as part of CombineExt.

Added `assign(to: on: ownership:)` operator

---

.github/workflows/tests.yml

This might help to resolve an issue with uploading code coverage results to Codecov
```
bash codecov.sh -n CombineExt -F  -y 
codecov.sh: illegal option -- y
Unexpected flag not supported
```
Codevcov has failed to upload the report in my [other PR](https://github.com/CombineCommunity/CombineExt/pull/54).

Bump Codecov action to 1.0.13

---

Sources/Relays/CurrentValueRelay.swift
Sources/Relays/PassthroughRelay.swift
Tests/CurrentValueRelayTests.swift
Tests/PassthroughRelayTests.swift

Fix for https://github.com/CombineCommunity/CombineExt/issues/37
I've added two new unit tests to confirm this issue. It seems that when you try to subscribe one relay to another
```swift
let input = CurrentValueRelay<String>("initial")
let output = CurrentValueRelay<String>("initial")
input
.subscribe(output)
.store(in: &subscriptions)
output
.sink(receiveCompletion: { _ in completed = true }, receiveValue: { self.values.append($0) })
.store(in: &subscriptions)
input.accept("1")
input.accept("2")
input.accept("3")
XCTAssertFalse(completed)
XCTAssertEqual(values, ["initial", "1", "2", "3"])
```
`subscribe()` doesn't work because the test fails. You can confirm it by replacing `subscribe()` with `sink { output.accept($0) }`
```swift
let input = CurrentValueRelay<String>("initial")
let …
```

Fixed issue with CurrentValueRelay and PassthroughRelay subscription

---

CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/IgnoreOutputSetOutputType.swift
Tests/IgnoreOutputSetOutputTypeTests.swift

@mbrandonw brought up a handy overload on `ignoreOutput` [in a discussion](https://github.com/pointfreeco/swift-composable-architecture/issues/271#issuecomment-682599562) over in TCA’s repository. I’d also be up for adding `ignoreFailure` and `ignoreFailure(setFailureType:)`, if you see fit.

Adds `ignoreOutput(setOutputType:)` overload.

---

CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/IgnoreFailure.swift
Sources/Operators/IgnoreOutputSetOutputType.swift
Tests/IgnoreFailureTests.swift

Mirroring `ignoreOutput` and `ignoreOutput(setOutputType:)` for the `Failure` generic. h/t @mbrandonw @stephencelis for [their discussion on this](https://github.com/pointfreeco/swift-composable-architecture/issues/271#issuecomment-682599562) and the feedback they filed (FB8563288).

Adds ignoreFailure(completeImmediately:) and ignoreFailure(setFailureType:completeImmediately:).

---

Sources/Subjects/ReplaySubject.swift
Tests/ReplaySubjectTests.swift

The locking I added in https://github.com/CombineCommunity/CombineExt/pull/72 was a bit too board — @sharplet noted:
> [sending messages to subscribers] while holding a lock can lead to a recursive call trying to take the same lock again and crashing.

Fine tunes ReplaySubject’s locking.

---

Sources/Subjects/ReplaySubject.swift
Tests/ShareReplayTests.swift

Attempts to fix https://github.com/CombineCommunity/CombineExt/issues/85
I added a test that proved that the source publisher was retained after everything had been nilled out/released.
I then added the `cancel()` method call in the `forwardCompletionToBuffer` method inside ReplaySubject.Subscription as this causes the subscription to then be released.
As I mentioned in the issue I raised, I'm not familiar enough to know what the other implications of this could be (it seems to all work fine for me in my project) so would appreciate any help or comments.

Share replay leak

---

Sources/Common/DemandBuffer.swift

I've recently been building a feature where I'm setting up a publisher using `Publishers.Create` on the main thread, and then sending values to the generated subscriber from another thread (this might an unsupported use-case for this publisher, let me know if so!). When debugging the code with Thread Sanitizer I get a warning about an access race:
```
SUMMARY: ThreadSanitizer: Swift access race (MyProject:arm64+0x1014d7318) in DemandBuffer.buffer(value:)+0x7c0
```
Looking at the code I can see that a `NSRecursiveLock` is used to protect the `demandState` inside of the DemandBuffer, but only in the `flush()` function. Since the `demandState` property is also accessed from within the `buffer(value:)` function my hunch is that this too should be protected by the lock. The use of the lock …

Add additional locking in DemandBuffer to protect demandState

---

README.md

This PR fixes a misspelling of `Cancellable` in README.md.

Fix misspelling of Cancellable in README.md

---

Package.swift

Hello!
This commit is meant to hide CombineSchedulers from the project using CombineExt.
Before it, a project would import:
After this commit, a project now imports:
In order to do so, we bumped swift-tools-version to 5.3 and altered the test target expression.
Please note that I am not a Package.swift nor a SPM expert, comments and feedbacks will be very appreciated. 
Thank you!

Package.swift: bump swift-tools-version to 5.3 and hide tests dependencies

---

Sources/Operators/PrefixDuration.swift
Sources/Subjects/ReplaySubject.swift

Also fixes Carthage build failure.
Reproducible by:
- Open CombineExt.xcodeproj in Xcode 13 RC
- Archive

Fix archiving project build failure

---

Sources/Operators/Materialize.swift
Tests/MaterializeTests.swift

This issue is easily reproducible by running the unit test I have added. The materialize operator will block any upstream work from being cancelled. The root cause seems to be due to a reference cycle where upstream has a reference to the sink, and the sink has a reference to upstream.  The cycle resolves after either a) upstream completes, or b) sink kills the upstream.  This is why simply nil'ing out the sink doesn't cancel upstream, because the sink deinit is not called.

Properly cancel upstream work when using Materialize operator.  Closes #108

---

Sources/Operators/Enumerated.swift
Tests/EnumeratedTests.swift

Added `enumerated()` operator similar to the one from [RxSwift](https://github.com/ReactiveX/RxSwift/blob/1a1fa37b0d08e0f99ffa41f98f340e8bc60c35c4/RxSwift/Observables/Enumerated.swift) and from [Swift](https://developer.apple.com/documentation/swift/array/1687832-enumerated).

Add `enumerated()` operator

---

Sources/Operators/WithLatestFrom.swift
Tests/WithLatestFromTests.swift

Fixing a memory leak in `withLatestFrom` operator as detailed in this issue https://github.com/CombineCommunity/CombineExt/issues/121

fix memory leak of receiver while using withLatestFrom operator

---

Sources/Operators/MapTo.swift
Sources/Operators/MapToValue.swift
Tests/MapToTests.swift
Tests/MapToValueTests.swift

Hello everyone!
After the latest update `1.6.0` our project that uses `CombineExt` stopped compiling with a wired error message. After some digging, I figured out that in some cases Swift confuses `map(to:)` extension with `map` operator and uses closure as a constant itself.
It can be reproduced with a test case that I added:
```swift
let fooSubject = PassthroughSubject<Int, Never>()
let barSubject = PassthroughSubject<Int, Never>()
let combinedPublisher = Publishers.CombineLatest(fooSubject, barSubject)
.map { fooItem, barItem in
fooItem * barItem // Error here: "ambiguous use of operator '*'"
}
// adding .eraseToAnyPublisher() will produce AnyPublisher<(Int, Int) -> Int, Never>
_ = combinedPublisher
.map {
"\($0)"
}
.sink {  
print($0)
}
fooSubject.send(5)
barSubject.send(6)
```
One …

⚠️ Fix `map(to:)` name collision

---

Sources/Operators/CombineLatestMany.swift
Sources/Operators/ZipMany.swift
Tests/CombineLatestManyTests.swift
Tests/ZipManyTests.swift

Previously combineLatest's implementation would trigger a stack overflow on 15000
publishers because the implementation combined its inputs linearly.
This commit replaces that with repeated (hierarchical) 4-way merges,
which lets the same scaled test scenario go to 1e7 publishers with no
issues (other than taking 28s to run the test on my M1 Pro, hence the
choice to commit the test with only 1e5 publishers). Test execution
wall-time scales linearly with publisher count.
Re: "4-way merge":
- Why not use a higher value? 4 is the highest arity offered by
Combine's Publisher.combineLatest.
- Why not use a lower value? Using 2-way merges instead of 4-way still
lets the 1e7 test case pass, but is ~60% slower (1e7 publishers take
45s insted of 28s).
All of the above applies remarkably similarly …

combineLatest & zip: make scalable using divide-and-conquer.

---

CombineExt.xcodeproj/project.pbxproj
README.md
Sources/Operators/PrefixWhileBehavior.swift
Tests/PrefixWhileBehaviorTests.swift

Figured we should add this to Ext after stumbling upon @jessegrosjean’s [Swift Forums thread](https://forums.swift.org/t/how-to-make-combines-prefix-operator-inclusive/39216) and @mayoff’s [approach with composed operators](https://forums.swift.org/t/how-to-make-combines-prefix-operator-inclusive/39216/8).

Adds Publisher.prefix(while:behavior:).

---

Sources/Subjects/ReplaySubject.swift
Tests/ReplaySubjectTests.swift

The ReplaySubject currently adds a new subscription before replaying the buffer. Since these two steps are not synchronized by the lock, it is possible that a new value is sent to the new subscription before the new subscription finishes replaying the buffer. This can result in a new subscription to a ReplaySubject receiving values out of order.
To fix this, it should be safe to have the new subscription replay the buffer before being added to the collection of subscriptions. The new subscription's DemandBuffer will have no requested demand at this point, so it will hold onto the replayed values until demand is requested. Once the lock is unlocked, any new values will be sent to all the subscriptions, which will always be added to the demand buffer after the replayed values.
I tried to …

Fix ReplaySubject race condition

---

Sources/Operators/MapToValue.swift
Tests/MapToValueTests.swift

After [fixing](https://github.com/CombineCommunity/CombineExt/pull/128) a `mapToValue` operator I got an idea to add `mapToVoid` operator. It's the most common use case for mapping publisher to a constant value. For example if you subscribe to `NotificationCenter` publisher and do not care about the value it produces:
```swift
NotificationCenter.default.publisher(for: UIApplication.userDidTakeScreenshotNotification)
.mapToVoid()
.sink {
// Do something
}
```

Add `mapToVoid` operator

---

CombineExt.xcodeproj/project.pbxproj
CombineExt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Operators/FlatMapFirst.swift
Tests/FlatMapFirstTests.swift

`FlatMapFirst` operator is a special case of `flatMap` operator.
Like `FlatMapLatest`, it only allows one inner publisher at a time. Unlike `FlatMapLatest`, it will not cancel an ongoing inner publisher.
Instead it ignores events from the source until the inner publisher is done. It creates another inner publisher only when the previous one is done.
Sources:
- https://danielt1263.medium.com/rxswifts-many-faces-of-flatmap-5764e6c2018c
- https://www.oreilly.com/library/view/mastering-reactive-javascript/9781786463388/298ee42c-d800-4228-87dd-a42d2ae6e820.xhtml
- https://github.com/ReactiveX/RxSwift/blob/1a1fa37b0d08e0f99ffa41f98f340e8bc60c35c4/RxSwift/Observables/Merge.swift

Implementation of FlatMapFirst operator

---

Sources/Operators/WithLatestFrom.swift
Tests/WithLatestFromTests.swift

Resolves #139 
The withLatestFrom stream has been completed, but it has been confirmed that `otherSubscription` is remaining and causing memory leaks.
Modified it to call `cancel` when `WithLatestFrom`'s `Subscription` is deinitialized.

Fix memory leak in WithLatestFrom
